service: sat-api

provider:
  name: aws

  runtime: nodejs12.x

  stage: ${opt:stage, 'production'}

  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::cbers-meta-pds*"
        - "arn:aws:s3:::landsat-pds*"
        - "arn:aws:s3:::sentinel-s2*"

  # deploymentBucket: remotepixel-${self:provider.region}

functions:
  landsat:
    handler: handler.landsat
    memorySize: 512
    timeout: 10
    events:
      - http:
          integration: lambda
          path: landsat
          method: get
          cors: true
          request:
            template:
              application/json: '{ "path" : "$input.params(''path'')", "row" : "$input.params(''row'')", "full" : "$input.params(''full'')" }'

  cbers:
    handler: handler.cbers
    memorySize: 512
    timeout: 10
    events:
      - http:
          integration: lambda
          path: cbers
          method: get
          cors: true
          request:
            template:
              application/json: '{ "path" : "$input.params(''path'')", "row" : "$input.params(''row'')" }'


  sentinel:
    handler: handler.sentinel
    memorySize: 512
    timeout: 10
    events:
      - http:
          integration: lambda
          path: sentinel
          method: get
          cors: true
          request:
            template:
              application/json: '{ "lat" : "$input.params(''lat'')", "long" : "$input.params(''long'')"}'

  home:
    handler: handler.home
    memorySize: 512
    timeout: 10
    events:
      - http:
          integration: lambda
          path: home
          method: get
          cors: true
          response:
              headers:
                      Content-Type: "'text/html'"
              template: $input.path('$')
